# syntax = edrevo/dockerfile-plus
INCLUDE+ ../Dockerfile.base

# Reset NODE_ENV=production
ENV NODE_ENV test

# Install dependencies for native builds and yarn
RUN apk add --no-cache make gcc g++ python git || \
    apk add --no-cache make gcc g++ python3 git # 'python' isn't available in alpine3.12+ \

CMD ["npm", "test"]

# All but package.json is optional
ONBUILD COPY package.json yarn.lock* .yarnrc* .npmrc* npm-shrinkwrap.json* package-lock.json* ./

ONBUILD RUN install-dependencies.sh

ONBUILD COPY . ./
