# Dockerfile.base and Dockerfile.test is included here through the release.sh script

# All but package.json is optional
ONBUILD COPY package.json yarn.lock* .yarnrc* .npmrc* npm-shrinkwrap.json* package-lock.json* ./

ONBUILD RUN install-dependencies.sh

ONBUILD COPY . ./
