FROM containers.schibsted.io/finntech/node:NODE_VERSION_TEMPLATE

# Reset NODE_ENV=production
ENV NODE_ENV test

# Install dependencies for native builds and yarn
RUN apk add --no-cache make gcc g++ python git

CMD ["npm", "test"]
